version: '3.9'
services:
  db:
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: whatremember
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

volumes:
  dbdata:
